#
# * @file            config/mid360.yaml
# * @description     
# * @author          rsazid99 <rsazid99@gmail.com>
# * @createTime      2026-04-22 23:53:22
# * @lastModified    2026-04-23 02:44:45
# * Copyright ©Sazid Rahman Simanto All rights reserved
#

lio_node:
  ros__parameters:
    imu_topic: '/livox/mid360/imu'
    lidar_topic: '/livox/mid360/lidar'
    init_imu_samples: 100
    #extrinsic parameter from lidar to imu sensor
    R_il: [
      1.0, 0.0, 0.0,
      0.0, 1.0, 0.0,
      0.0, 0.0, 1.0
    ]
    t_il: [-0.011, -0.02329, 0.04412]
    acc_scale: 1.0
    gyro_noise_std: 0.1
    acc_noise_std: 0.01
    gyro_bias_noise_std: 0.001
    acc_bias_noise_std: 0.0001
    gravity_noise_std: 0.001